[tool.poetry]
name = "attractors"
version = "0.1.0"
description = ""
authors = ["BCarnaval <antoinedelagrave@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
